name: Update Index

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          echo '<html><body><h1>File Downloads</h1><ul>' > index.html
          for file in $(find . -type f ! -name 'index.html' ! -path './.git/*'); do
            echo "<li><a href='$file'>$(basename $file)</a></li>" >> index.html
          done
          echo '</ul></body></html>' >> index.html

      - name: Commit and push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Update index.html with download links'
          git push https://${{ secrets.ACTIONS_PAT }}@github.com/anir0y/dl.arishtisecurity.com.git
